"""Implementation of statechart flower_controller.
Generated by itemis CREATE code generator.
"""

import sys, os
from flower.src.yakindu.rx import Observable
from flower.src.yakindu.rx import StartFlowerAppObserver, TerminateTrainingObserver, CreateErrorLogObservableObserver, TaskCompleteObserver, TaskErrorObserver

class FlowerController:
	"""Implementation of the state machine FlowerController.
	"""

	class State:
		""" State Enum
		"""
		(
			flower_controller_s3__internal_error,
			flower_controller_s0__idle,
			flower_controller_s1__start_flower_app,
			flower_controller_s2__termination,
			null_state
		) = range(5)
	
	
	class AiTrPlatEvBuf:
		"""Implementation of internal scope.
		"""
		
		def __init__(self):
			self.task_start = False
			self.training_complete = False
			self.stop_training = False
			self.termination_complete = False
			self.termination_fail = False
			self.internal_error = False
			self.create_error_log_complete = False
	
	class FlowerControllerEvBuf:
		"""Implementation of internal scope.
		"""
		
		def __init__(self, iface_ai_tr_plat):
			self.iface_ai_tr_plat = iface_ai_tr_plat
	
	class AiTrPlat:
		"""Implementation of scope AiTrPlat.
		"""
		
		def __init__(self, statemachine):
			self.task_start = None
			self.training_complete = None
			self.stop_training = None
			self.termination_complete = None
			self.termination_fail = None
			self.internal_error = None
			self.create_error_log_complete = None
			self.start_flower_app = None
			self.start_flower_app_observable = Observable()
			self.start_flower_app_observable.subscribe(StartFlowerAppObserver())
			self.terminate_training = None
			self.terminate_training_observable = Observable()
			self.terminate_training_observable.subscribe(TerminateTrainingObserver())
			self.create_error_log = None
			self.create_error_log_observable = Observable()
			self.create_error_log_observable.subscribe(CreateErrorLogObservableObserver())
			self.task_complete = None
			self.task_complete_observable = Observable()
			self.task_complete_observable.subscribe(TaskCompleteObserver())
			self.task_error = None
			self.task_error_observable = Observable()
			self.task_error_observable.subscribe(TaskErrorObserver())
			
			self.statemachine = statemachine
		
		def raise_task_start(self):
			"""Raise method for event task_start.
			"""
			self.task_start = True
			
		def raise_training_complete(self):
			"""Raise method for event training_complete.
			"""
			self.training_complete = True
			
		def raise_stop_training(self):
			"""Raise method for event stop_training.
			"""
			self.stop_training = True
			
		def raise_termination_complete(self):
			"""Raise method for event termination_complete.
			"""
			self.termination_complete = True
			
		def raise_termination_fail(self):
			"""Raise method for event termination_fail.
			"""
			self.termination_fail = True
			
		def raise_internal_error(self):
			"""Raise method for event internal_error.
			"""
			self.internal_error = True
			
		def raise_create_error_log_complete(self):
			"""Raise method for event create_error_log_complete.
			"""
			self.create_error_log_complete = True
			
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		self.ai_tr_plat = FlowerController.AiTrPlat(self)
		
		# enumeration of all states:
		self.__State = FlowerController.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 1
		for __state_index in range(1):
			self.__state_vector[__state_index] = self.State.null_state
		
		# initializations:
		self.__current = self.FlowerControllerEvBuf(
			self.AiTrPlatEvBuf()
		)
		self.__is_executing = False
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.flower_controller_s3__internal_error:
			return self.__state_vector[0] == self.__State.flower_controller_s3__internal_error
		if s == self.__State.flower_controller_s0__idle:
			return self.__state_vector[0] == self.__State.flower_controller_s0__idle
		if s == self.__State.flower_controller_s1__start_flower_app:
			return self.__state_vector[0] == self.__State.flower_controller_s1__start_flower_app
		if s == self.__State.flower_controller_s2__termination:
			return self.__state_vector[0] == self.__State.flower_controller_s2__termination
		return False
		
	def __enter_sequence_flower_controller_s3__internal_error_default(self):
		"""'default' enter sequence for state S3: InternalError.
		"""
		#'default' enter sequence for state S3: InternalError
		self.__state_vector[0] = self.State.flower_controller_s3__internal_error
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_flower_controller_s0__idle_default(self):
		"""'default' enter sequence for state S0: IDLE.
		"""
		#'default' enter sequence for state S0: IDLE
		self.__state_vector[0] = self.State.flower_controller_s0__idle
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_flower_controller_s1__start_flower_app_default(self):
		"""'default' enter sequence for state S1: StartFlowerApp.
		"""
		#'default' enter sequence for state S1: StartFlowerApp
		self.__state_vector[0] = self.State.flower_controller_s1__start_flower_app
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_flower_controller_s2__termination_default(self):
		"""'default' enter sequence for state S2: Termination.
		"""
		#'default' enter sequence for state S2: Termination
		self.__state_vector[0] = self.State.flower_controller_s2__termination
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_flower_controller_default(self):
		"""'default' enter sequence for region FlowerController.
		"""
		#'default' enter sequence for region FlowerController
		self.__react_flower_controller__entry_default()
		
	def __exit_sequence_flower_controller_s3__internal_error(self):
		"""Default exit sequence for state S3: InternalError.
		"""
		#Default exit sequence for state S3: InternalError
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_flower_controller_s0__idle(self):
		"""Default exit sequence for state S0: IDLE.
		"""
		#Default exit sequence for state S0: IDLE
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_flower_controller_s1__start_flower_app(self):
		"""Default exit sequence for state S1: StartFlowerApp.
		"""
		#Default exit sequence for state S1: StartFlowerApp
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_flower_controller_s2__termination(self):
		"""Default exit sequence for state S2: Termination.
		"""
		#Default exit sequence for state S2: Termination
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_flower_controller(self):
		"""Default exit sequence for region FlowerController.
		"""
		#Default exit sequence for region FlowerController
		state = self.__state_vector[0]
		if state == self.State.flower_controller_s3__internal_error:
			self.__exit_sequence_flower_controller_s3__internal_error()
		elif state == self.State.flower_controller_s0__idle:
			self.__exit_sequence_flower_controller_s0__idle()
		elif state == self.State.flower_controller_s1__start_flower_app:
			self.__exit_sequence_flower_controller_s1__start_flower_app()
		elif state == self.State.flower_controller_s2__termination:
			self.__exit_sequence_flower_controller_s2__termination()
		
	def __react_flower_controller__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_flower_controller_s0__idle_default()
		
	def __flower_controller_s3__internal_error_react(self, transitioned_before):
		"""Implementation of __flower_controller_s3__internal_error_react function.
		"""
		#The reactions of state S3: InternalError.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_ai_tr_plat.create_error_log_complete:
				self.__exit_sequence_flower_controller_s3__internal_error()
				self.ai_tr_plat.task_error_observable.next()
				self.__enter_sequence_flower_controller_s0__idle_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __flower_controller_s0__idle_react(self, transitioned_before):
		"""Implementation of __flower_controller_s0__idle_react function.
		"""
		#The reactions of state S0: IDLE.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_ai_tr_plat.task_start:
				self.__exit_sequence_flower_controller_s0__idle()
				self.ai_tr_plat.start_flower_app_observable.next()
				self.__enter_sequence_flower_controller_s1__start_flower_app_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __flower_controller_s1__start_flower_app_react(self, transitioned_before):
		"""Implementation of __flower_controller_s1__start_flower_app_react function.
		"""
		#The reactions of state S1: StartFlowerApp.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_ai_tr_plat.internal_error:
				self.__exit_sequence_flower_controller_s1__start_flower_app()
				self.ai_tr_plat.create_error_log_observable.next()
				self.__enter_sequence_flower_controller_s3__internal_error_default()
				transitioned_after = 0
			elif self.__current.iface_ai_tr_plat.stop_training:
				self.__exit_sequence_flower_controller_s1__start_flower_app()
				self.ai_tr_plat.terminate_training_observable.next()
				self.__enter_sequence_flower_controller_s2__termination_default()
				transitioned_after = 0
			elif self.__current.iface_ai_tr_plat.training_complete:
				self.__exit_sequence_flower_controller_s1__start_flower_app()
				self.ai_tr_plat.task_complete_observable.next()
				self.__enter_sequence_flower_controller_s0__idle_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __flower_controller_s2__termination_react(self, transitioned_before):
		"""Implementation of __flower_controller_s2__termination_react function.
		"""
		#The reactions of state S2: Termination.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_ai_tr_plat.termination_complete:
				self.__exit_sequence_flower_controller_s2__termination()
				self.ai_tr_plat.task_complete_observable.next()
				self.__enter_sequence_flower_controller_s0__idle_default()
				transitioned_after = 0
			elif self.__current.iface_ai_tr_plat.termination_fail:
				self.__exit_sequence_flower_controller_s2__termination()
				self.ai_tr_plat.create_error_log_observable.next()
				self.__enter_sequence_flower_controller_s3__internal_error_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __swap_in_events(self):
		"""Implementation of __swap_in_events function.
		"""
		self.__current.iface_ai_tr_plat.task_start = self.ai_tr_plat.task_start
		self.ai_tr_plat.task_start = False
		self.__current.iface_ai_tr_plat.training_complete = self.ai_tr_plat.training_complete
		self.ai_tr_plat.training_complete = False
		self.__current.iface_ai_tr_plat.stop_training = self.ai_tr_plat.stop_training
		self.ai_tr_plat.stop_training = False
		self.__current.iface_ai_tr_plat.termination_complete = self.ai_tr_plat.termination_complete
		self.ai_tr_plat.termination_complete = False
		self.__current.iface_ai_tr_plat.termination_fail = self.ai_tr_plat.termination_fail
		self.ai_tr_plat.termination_fail = False
		self.__current.iface_ai_tr_plat.internal_error = self.ai_tr_plat.internal_error
		self.ai_tr_plat.internal_error = False
		self.__current.iface_ai_tr_plat.create_error_log_complete = self.ai_tr_plat.create_error_log_complete
		self.ai_tr_plat.create_error_log_complete = False
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.ai_tr_plat.task_start = False
		self.ai_tr_plat.training_complete = False
		self.ai_tr_plat.stop_training = False
		self.ai_tr_plat.termination_complete = False
		self.ai_tr_plat.termination_fail = False
		self.ai_tr_plat.internal_error = False
		self.ai_tr_plat.create_error_log_complete = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		state = self.__state_vector[0]
		if state == self.State.flower_controller_s3__internal_error:
			self.__flower_controller_s3__internal_error_react(-1)
		elif state == self.State.flower_controller_s0__idle:
			self.__flower_controller_s0__idle_react(-1)
		elif state == self.State.flower_controller_s1__start_flower_app:
			self.__flower_controller_s1__start_flower_app_react(-1)
		elif state == self.State.flower_controller_s2__termination:
			self.__flower_controller_s2__termination_react(-1)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		#Performs a 'run to completion' step.
		if self.__is_executing:
			return
		self.__is_executing = True
		self.__swap_in_events()
		self.__micro_step()
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		#Activates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default enter sequence for statechart FlowerController
		self.__enter_sequence_flower_controller_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		#Deactivates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default exit sequence for statechart FlowerController
		self.__exit_sequence_flower_controller()
		self.__state_vector[0] = self.State.null_state
		self.__is_executing = False
	
	
