"""Implementation of statechart apiserver.
Generated by itemis CREATE code generator.
"""

import sys, os
from apiserver.src.yakindu.rx import Observable
from apiserver.src.yakindu.rx import CheckConfigObserver, ErrorReportObserver, CountDBDataObserver, PullDataRequestObserver, PushInTaskQueueObserver, DeleteAppObserver
from apiserver.src.yakindu.callback_func import CallBackFunc

class APIServer:
	"""Implementation of the state machine APIServer.
	"""

	class State:
		""" State Enum
		"""
		(
			apiserver_s0__idle,
			apiserver_s1__configuration,
			apiserver_s6__error_state,
			apiserver_s3__data_collection,
			apiserver_s3__data_collection_data_collection____count_dbdata,
			apiserver_s3__data_collection_data_collection____pull_data,
			apiserver_s4__queuing,
			apiserver_s5__delete,
			null_state
		) = range(9)
	
	
	class AppPlatEvBuf:
		"""Implementation of internal scope.
		"""
		
		def __init__(self):
			self.retrain = False
			self.delete = False
			self.receive_report = False
	
	class CommonDBEvBuf:
		"""Implementation of internal scope.
		"""
		
		def __init__(self):
			self.count_data_response = False
			self.count_data_fail = False
			self.data_pull_complete = False
			self.data_pull_fail = False
			self.save_model_success = False
			self.save_model_fail = False
	
	class AiTrPlatEvBuf:
		"""Implementation of internal scope.
		"""
		
		def __init__(self):
			self.check_config_complete = False
			self.check_config_fail = False
			self.push_task_complete = False
			self.push_task_fail = False
			self.delete_app_complete = False
			self.delete_app_fail = False
	
	class APIServerEvBuf:
		"""Implementation of internal scope.
		"""
		
		def __init__(self, iface_app_plat, iface_common_db, iface_ai_tr_plat):
			self.iface_app_plat = iface_app_plat
			self.iface_common_db = iface_common_db
			self.iface_ai_tr_plat = iface_ai_tr_plat
	
	class AppPlat:
		"""Implementation of scope AppPlat.
		"""
		
		def __init__(self, statemachine):
			self.retrain = None
			self.delete = None
			self.receive_report = None
			
			self.statemachine = statemachine
		
		def raise_retrain(self):
			"""Raise method for event retrain.
			"""
			self.retrain = True
			
		def raise_delete(self):
			"""Raise method for event delete.
			"""
			self.delete = True
			
		def raise_receive_report(self):
			"""Raise method for event receive_report.
			"""
			self.receive_report = True
			
	
	class CommonDB:
		"""Implementation of scope CommonDB.
		"""
		
		def __init__(self, statemachine):
			self.count_data_response = None
			self.count_data_fail = None
			self.data_pull_complete = None
			self.data_pull_fail = None
			self.save_model_success = None
			self.save_model_fail = None
			
			self.statemachine = statemachine
		
		def raise_count_data_response(self):
			"""Raise method for event count_data_response.
			"""
			self.count_data_response = True
			
		def raise_count_data_fail(self):
			"""Raise method for event count_data_fail.
			"""
			self.count_data_fail = True
			
		def raise_data_pull_complete(self):
			"""Raise method for event data_pull_complete.
			"""
			self.data_pull_complete = True
			
		def raise_data_pull_fail(self):
			"""Raise method for event data_pull_fail.
			"""
			self.data_pull_fail = True
			
		def raise_save_model_success(self):
			"""Raise method for event save_model_success.
			"""
			self.save_model_success = True
			
		def raise_save_model_fail(self):
			"""Raise method for event save_model_fail.
			"""
			self.save_model_fail = True
			
	
	class AiTrPlat:
		"""Implementation of scope AiTrPlat.
		"""
		
		def __init__(self, statemachine):
			self.valid_config = None
			self.num_data = None
			self.DATA_CONSTRAINT = 10000
			self.check_config_complete = None
			self.check_config_fail = None
			self.push_task_complete = None
			self.push_task_fail = None
			self.delete_app_complete = None
			self.delete_app_fail = None
			self.check_config = None
			self.check_config_observable = Observable()
			self.check_config_observable.subscribe(CheckConfigObserver())
			self.error_report = None
			self.error_report_observable = Observable()
			self.error_report_observable.subscribe(ErrorReportObserver())
			self.count_db_data = None
			self.count_db_data_observable = Observable()
			self.count_db_data_observable.subscribe(CountDBDataObserver())
			self.pull_data_request = None
			self.pull_data_request_observable = Observable()
			self.pull_data_request_observable.subscribe(PullDataRequestObserver())
			self.push_in_task_queue = None
			self.push_in_task_queue_observable = Observable()
			self.push_in_task_queue_observable.subscribe(PushInTaskQueueObserver())
			self.delete_app = None
			self.delete_app_observable = Observable()
			self.delete_app_observable.subscribe(DeleteAppObserver())
			self.operation_callback = CallBackFunc()
			
			self.statemachine = statemachine
		
		def raise_check_config_complete(self):
			"""Raise method for event check_config_complete.
			"""
			self.check_config_complete = True
			
		def raise_check_config_fail(self):
			"""Raise method for event check_config_fail.
			"""
			self.check_config_fail = True
			
		def raise_push_task_complete(self):
			"""Raise method for event push_task_complete.
			"""
			self.push_task_complete = True
			
		def raise_push_task_fail(self):
			"""Raise method for event push_task_fail.
			"""
			self.push_task_fail = True
			
		def raise_delete_app_complete(self):
			"""Raise method for event delete_app_complete.
			"""
			self.delete_app_complete = True
			
		def raise_delete_app_fail(self):
			"""Raise method for event delete_app_fail.
			"""
			self.delete_app_fail = True
			
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		self.app_plat = APIServer.AppPlat(self)
		self.common_db = APIServer.CommonDB(self)
		self.ai_tr_plat = APIServer.AiTrPlat(self)
		
		# enumeration of all states:
		self.__State = APIServer.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 1
		for __state_index in range(1):
			self.__state_vector[__state_index] = self.State.null_state
		
		# initializations:
		#Default init sequence for statechart APIServer
		self.ai_tr_plat.valid_config = False
		self.ai_tr_plat.num_data = 0
		self.__current = self.APIServerEvBuf(
			self.AppPlatEvBuf(), 
			self.CommonDBEvBuf(), 
			self.AiTrPlatEvBuf()
		)
		self.__is_executing = False
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.apiserver_s0__idle:
			return self.__state_vector[0] == self.__State.apiserver_s0__idle
		if s == self.__State.apiserver_s1__configuration:
			return self.__state_vector[0] == self.__State.apiserver_s1__configuration
		if s == self.__State.apiserver_s6__error_state:
			return self.__state_vector[0] == self.__State.apiserver_s6__error_state
		if s == self.__State.apiserver_s3__data_collection:
			return (self.__state_vector[0] >= self.__State.apiserver_s3__data_collection)\
				and (self.__state_vector[0] <= self.__State.apiserver_s3__data_collection_data_collection____pull_data)
		if s == self.__State.apiserver_s3__data_collection_data_collection____count_dbdata:
			return self.__state_vector[0] == self.__State.apiserver_s3__data_collection_data_collection____count_dbdata
		if s == self.__State.apiserver_s3__data_collection_data_collection____pull_data:
			return self.__state_vector[0] == self.__State.apiserver_s3__data_collection_data_collection____pull_data
		if s == self.__State.apiserver_s4__queuing:
			return self.__state_vector[0] == self.__State.apiserver_s4__queuing
		if s == self.__State.apiserver_s5__delete:
			return self.__state_vector[0] == self.__State.apiserver_s5__delete
		return False
		
	def __enter_sequence_apiserver_s0__idle_default(self):
		"""'default' enter sequence for state S0: IDLE.
		"""
		#'default' enter sequence for state S0: IDLE
		self.__state_vector[0] = self.State.apiserver_s0__idle
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_apiserver_s1__configuration_default(self):
		"""'default' enter sequence for state S1: Configuration.
		"""
		#'default' enter sequence for state S1: Configuration
		self.__state_vector[0] = self.State.apiserver_s1__configuration
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_apiserver_s6__error_state_default(self):
		"""'default' enter sequence for state S6: Error State.
		"""
		#'default' enter sequence for state S6: Error State
		self.__state_vector[0] = self.State.apiserver_s6__error_state
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_apiserver_s3__data_collection_default(self):
		"""'default' enter sequence for state S3: DataCollection.
		"""
		#'default' enter sequence for state S3: DataCollection
		self.__enter_sequence_apiserver_s3__data_collection_data_collection_____default()
		
	def __enter_sequence_apiserver_s3__data_collection_data_collection_____count_dbdata_default(self):
		"""'default' enter sequence for state CountDBData.
		"""
		#'default' enter sequence for state CountDBData
		self.__state_vector[0] = self.State.apiserver_s3__data_collection_data_collection____count_dbdata
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_apiserver_s3__data_collection_data_collection_____pull_data_default(self):
		"""'default' enter sequence for state PullData.
		"""
		#'default' enter sequence for state PullData
		self.__state_vector[0] = self.State.apiserver_s3__data_collection_data_collection____pull_data
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_apiserver_s4__queuing_default(self):
		"""'default' enter sequence for state S4: Queuing.
		"""
		#'default' enter sequence for state S4: Queuing
		self.__state_vector[0] = self.State.apiserver_s4__queuing
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_apiserver_s5__delete_default(self):
		"""'default' enter sequence for state S5: Delete.
		"""
		#'default' enter sequence for state S5: Delete
		self.__state_vector[0] = self.State.apiserver_s5__delete
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_apiserver_default(self):
		"""'default' enter sequence for region APIServer.
		"""
		#'default' enter sequence for region APIServer
		self.__react_apiserver__entry_default()
		
	def __enter_sequence_apiserver_s3__data_collection_data_collection_____default(self):
		"""'default' enter sequence for region DataCollection    .
		"""
		#'default' enter sequence for region DataCollection    
		self.__react_apiserver_s3__data_collection_data_collection______entry_default()
		
	def __exit_sequence_apiserver_s0__idle(self):
		"""Default exit sequence for state S0: IDLE.
		"""
		#Default exit sequence for state S0: IDLE
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_apiserver_s1__configuration(self):
		"""Default exit sequence for state S1: Configuration.
		"""
		#Default exit sequence for state S1: Configuration
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_apiserver_s6__error_state(self):
		"""Default exit sequence for state S6: Error State.
		"""
		#Default exit sequence for state S6: Error State
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_apiserver_s3__data_collection(self):
		"""Default exit sequence for state S3: DataCollection.
		"""
		#Default exit sequence for state S3: DataCollection
		self.__exit_sequence_apiserver_s3__data_collection_data_collection____()
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_apiserver_s3__data_collection_data_collection_____count_dbdata(self):
		"""Default exit sequence for state CountDBData.
		"""
		#Default exit sequence for state CountDBData
		self.__state_vector[0] = self.State.apiserver_s3__data_collection
		
	def __exit_sequence_apiserver_s3__data_collection_data_collection_____pull_data(self):
		"""Default exit sequence for state PullData.
		"""
		#Default exit sequence for state PullData
		self.__state_vector[0] = self.State.apiserver_s3__data_collection
		
	def __exit_sequence_apiserver_s4__queuing(self):
		"""Default exit sequence for state S4: Queuing.
		"""
		#Default exit sequence for state S4: Queuing
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_apiserver_s5__delete(self):
		"""Default exit sequence for state S5: Delete.
		"""
		#Default exit sequence for state S5: Delete
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_apiserver(self):
		"""Default exit sequence for region APIServer.
		"""
		#Default exit sequence for region APIServer
		state = self.__state_vector[0]
		if state == self.State.apiserver_s0__idle:
			self.__exit_sequence_apiserver_s0__idle()
		elif state == self.State.apiserver_s1__configuration:
			self.__exit_sequence_apiserver_s1__configuration()
		elif state == self.State.apiserver_s6__error_state:
			self.__exit_sequence_apiserver_s6__error_state()
		elif state == self.State.apiserver_s3__data_collection:
			self.__exit_sequence_apiserver_s3__data_collection()
		elif state == self.State.apiserver_s3__data_collection_data_collection____count_dbdata:
			self.__exit_sequence_apiserver_s3__data_collection_data_collection_____count_dbdata()
		elif state == self.State.apiserver_s3__data_collection_data_collection____pull_data:
			self.__exit_sequence_apiserver_s3__data_collection_data_collection_____pull_data()
		elif state == self.State.apiserver_s4__queuing:
			self.__exit_sequence_apiserver_s4__queuing()
		elif state == self.State.apiserver_s5__delete:
			self.__exit_sequence_apiserver_s5__delete()
		
	def __exit_sequence_apiserver_s3__data_collection_data_collection____(self):
		"""Default exit sequence for region DataCollection    .
		"""
		#Default exit sequence for region DataCollection    
		state = self.__state_vector[0]
		if state == self.State.apiserver_s3__data_collection_data_collection____count_dbdata:
			self.__exit_sequence_apiserver_s3__data_collection_data_collection_____count_dbdata()
		elif state == self.State.apiserver_s3__data_collection_data_collection____pull_data:
			self.__exit_sequence_apiserver_s3__data_collection_data_collection_____pull_data()
		
	def __react_apiserver__choice_0(self):
		"""The reactions of state null..
		"""
		#The reactions of state null.
		if self.ai_tr_plat.valid_config:
			self.ai_tr_plat.count_db_data_observable.next()
			self.__enter_sequence_apiserver_s3__data_collection_default()
		else:
			self.ai_tr_plat.error_report_observable.next()
			self.__enter_sequence_apiserver_s6__error_state_default()
		
	def __react_apiserver_s3__data_collection_data_collection______choice_0(self):
		"""The reactions of state null..
		"""
		#The reactions of state null.
		if self.ai_tr_plat.num_data >= self.ai_tr_plat.DATA_CONSTRAINT:
			self.ai_tr_plat.pull_data_request_observable.next()
			self.__enter_sequence_apiserver_s3__data_collection_data_collection_____pull_data_default()
		else:
			self.__exit_sequence_apiserver_s3__data_collection()
			self.ai_tr_plat.error_report_observable.next()
			self.__enter_sequence_apiserver_s6__error_state_default()
		
	def __react_apiserver__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_apiserver_s0__idle_default()
		
	def __react_apiserver_s3__data_collection_data_collection______entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_apiserver_s3__data_collection_data_collection_____count_dbdata_default()
		
	def __apiserver_s0__idle_react(self, transitioned_before):
		"""Implementation of __apiserver_s0__idle_react function.
		"""
		#The reactions of state S0: IDLE.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_app_plat.retrain:
				self.__exit_sequence_apiserver_s0__idle()
				self.ai_tr_plat.check_config_observable.next()
				self.__enter_sequence_apiserver_s1__configuration_default()
				transitioned_after = 0
			elif self.__current.iface_app_plat.delete:
				self.__exit_sequence_apiserver_s0__idle()
				self.ai_tr_plat.delete_app_observable.next()
				self.__enter_sequence_apiserver_s5__delete_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __apiserver_s1__configuration_react(self, transitioned_before):
		"""Implementation of __apiserver_s1__configuration_react function.
		"""
		#The reactions of state S1: Configuration.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_ai_tr_plat.check_config_complete:
				self.__exit_sequence_apiserver_s1__configuration()
				self.ai_tr_plat.valid_config = self.ai_tr_plat.operation_callback.get_config_result()
				self.__react_apiserver__choice_0()
				transitioned_after = 0
			elif self.__current.iface_ai_tr_plat.check_config_fail:
				self.__exit_sequence_apiserver_s1__configuration()
				self.ai_tr_plat.error_report_observable.next()
				self.__enter_sequence_apiserver_s6__error_state_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __apiserver_s6__error_state_react(self, transitioned_before):
		"""Implementation of __apiserver_s6__error_state_react function.
		"""
		#The reactions of state S6: Error State.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_app_plat.receive_report:
				self.__exit_sequence_apiserver_s6__error_state()
				self.__enter_sequence_apiserver_s0__idle_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __apiserver_s3__data_collection_data_collection_____count_dbdata_react(self, transitioned_before):
		"""Implementation of __apiserver_s3__data_collection_data_collection_____count_dbdata_react function.
		"""
		#The reactions of state CountDBData.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_common_db.count_data_response:
				self.__exit_sequence_apiserver_s3__data_collection_data_collection_____count_dbdata()
				self.ai_tr_plat.num_data = self.ai_tr_plat.operation_callback.get_num_data()
				self.__react_apiserver_s3__data_collection_data_collection______choice_0()
				transitioned_after = 0
			elif self.__current.iface_common_db.count_data_fail:
				self.__exit_sequence_apiserver_s3__data_collection()
				self.ai_tr_plat.error_report_observable.next()
				self.__enter_sequence_apiserver_s6__error_state_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __apiserver_s3__data_collection_data_collection_____pull_data_react(self, transitioned_before):
		"""Implementation of __apiserver_s3__data_collection_data_collection_____pull_data_react function.
		"""
		#The reactions of state PullData.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_common_db.data_pull_complete:
				self.__exit_sequence_apiserver_s3__data_collection()
				self.ai_tr_plat.push_in_task_queue_observable.next()
				self.__enter_sequence_apiserver_s4__queuing_default()
				transitioned_after = 0
			elif self.__current.iface_common_db.data_pull_fail:
				self.__exit_sequence_apiserver_s3__data_collection()
				self.ai_tr_plat.error_report_observable.next()
				self.__enter_sequence_apiserver_s6__error_state_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __apiserver_s4__queuing_react(self, transitioned_before):
		"""Implementation of __apiserver_s4__queuing_react function.
		"""
		#The reactions of state S4: Queuing.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_ai_tr_plat.push_task_fail:
				self.__exit_sequence_apiserver_s4__queuing()
				self.ai_tr_plat.error_report_observable.next()
				self.__enter_sequence_apiserver_s6__error_state_default()
				transitioned_after = 0
			elif self.__current.iface_ai_tr_plat.push_task_complete:
				self.__exit_sequence_apiserver_s4__queuing()
				self.__enter_sequence_apiserver_s0__idle_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __apiserver_s5__delete_react(self, transitioned_before):
		"""Implementation of __apiserver_s5__delete_react function.
		"""
		#The reactions of state S5: Delete.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__current.iface_ai_tr_plat.delete_app_complete:
				self.__exit_sequence_apiserver_s5__delete()
				self.__enter_sequence_apiserver_s0__idle_default()
				transitioned_after = 0
			elif self.__current.iface_ai_tr_plat.delete_app_fail:
				self.__exit_sequence_apiserver_s5__delete()
				self.ai_tr_plat.error_report_observable.next()
				self.__enter_sequence_apiserver_s6__error_state_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __swap_in_events(self):
		"""Implementation of __swap_in_events function.
		"""
		self.__current.iface_app_plat.retrain = self.app_plat.retrain
		self.app_plat.retrain = False
		self.__current.iface_app_plat.delete = self.app_plat.delete
		self.app_plat.delete = False
		self.__current.iface_app_plat.receive_report = self.app_plat.receive_report
		self.app_plat.receive_report = False
		self.__current.iface_common_db.count_data_response = self.common_db.count_data_response
		self.common_db.count_data_response = False
		self.__current.iface_common_db.count_data_fail = self.common_db.count_data_fail
		self.common_db.count_data_fail = False
		self.__current.iface_common_db.data_pull_complete = self.common_db.data_pull_complete
		self.common_db.data_pull_complete = False
		self.__current.iface_common_db.data_pull_fail = self.common_db.data_pull_fail
		self.common_db.data_pull_fail = False
		self.__current.iface_common_db.save_model_success = self.common_db.save_model_success
		self.common_db.save_model_success = False
		self.__current.iface_common_db.save_model_fail = self.common_db.save_model_fail
		self.common_db.save_model_fail = False
		self.__current.iface_ai_tr_plat.check_config_complete = self.ai_tr_plat.check_config_complete
		self.ai_tr_plat.check_config_complete = False
		self.__current.iface_ai_tr_plat.check_config_fail = self.ai_tr_plat.check_config_fail
		self.ai_tr_plat.check_config_fail = False
		self.__current.iface_ai_tr_plat.push_task_complete = self.ai_tr_plat.push_task_complete
		self.ai_tr_plat.push_task_complete = False
		self.__current.iface_ai_tr_plat.push_task_fail = self.ai_tr_plat.push_task_fail
		self.ai_tr_plat.push_task_fail = False
		self.__current.iface_ai_tr_plat.delete_app_complete = self.ai_tr_plat.delete_app_complete
		self.ai_tr_plat.delete_app_complete = False
		self.__current.iface_ai_tr_plat.delete_app_fail = self.ai_tr_plat.delete_app_fail
		self.ai_tr_plat.delete_app_fail = False
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.app_plat.retrain = False
		self.app_plat.delete = False
		self.app_plat.receive_report = False
		self.common_db.count_data_response = False
		self.common_db.count_data_fail = False
		self.common_db.data_pull_complete = False
		self.common_db.data_pull_fail = False
		self.common_db.save_model_success = False
		self.common_db.save_model_fail = False
		self.ai_tr_plat.check_config_complete = False
		self.ai_tr_plat.check_config_fail = False
		self.ai_tr_plat.push_task_complete = False
		self.ai_tr_plat.push_task_fail = False
		self.ai_tr_plat.delete_app_complete = False
		self.ai_tr_plat.delete_app_fail = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		state = self.__state_vector[0]
		if state == self.State.apiserver_s0__idle:
			self.__apiserver_s0__idle_react(-1)
		elif state == self.State.apiserver_s1__configuration:
			self.__apiserver_s1__configuration_react(-1)
		elif state == self.State.apiserver_s6__error_state:
			self.__apiserver_s6__error_state_react(-1)
		elif state == self.State.apiserver_s3__data_collection_data_collection____count_dbdata:
			self.__apiserver_s3__data_collection_data_collection_____count_dbdata_react(-1)
		elif state == self.State.apiserver_s3__data_collection_data_collection____pull_data:
			self.__apiserver_s3__data_collection_data_collection_____pull_data_react(-1)
		elif state == self.State.apiserver_s4__queuing:
			self.__apiserver_s4__queuing_react(-1)
		elif state == self.State.apiserver_s5__delete:
			self.__apiserver_s5__delete_react(-1)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		#Performs a 'run to completion' step.
		if self.ai_tr_plat.operation_callback is None:
			raise ValueError("Operation callback for interface AiTrPlat must be set.")
		
		if self.__is_executing:
			return
		self.__is_executing = True
		self.__swap_in_events()
		self.__micro_step()
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		#Activates the state machine.
		if self.ai_tr_plat.operation_callback is None:
			raise ValueError("Operation callback for interface AiTrPlat must be set.")
		
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default enter sequence for statechart APIServer
		self.__enter_sequence_apiserver_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		#Deactivates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default exit sequence for statechart APIServer
		self.__exit_sequence_apiserver()
		self.__state_vector[0] = self.State.null_state
		self.__is_executing = False
	
	
