"""Implementation for Observer and Observables used for out events.
Generated by itemis CREATE code generator.
"""

import requests
import sys, os

class Observer():
	"""Observer implementation.
	"""

	def next(self, value=None):
		"""Abstract next method, which must be implemented."""
		raise NotImplementedError('user must define next() to use this base class')
	
class TaskStartObserver():
	def next(self, value=None):
		try:
			print("Raise task start:", value)
		except Exception as e:
			print("Error Code 203 [OUT_EVENT_ERROR]: Error in Task Queue Controller out event TaskStartObserver:", e)

class StopTrainingObserver():
	def next(self, value=None):
		try:
			print("Raise stop training:", value)
		except Exception as e:
			print("Error Code 203 [OUT_EVENT_ERROR]: Error in Task Queue Controller out event StopTrainingObserver:", e)

class PushObserver():
	def next(self, value=None):
		controller_url = os.environ.get("API_SERVER_URL", "http://localhost:3032/fl_training_task_queue/push")
		try:
			print("Task Queue Controller raises push task")
			response = requests.post(controller_url, timeout=10)
		except Exception as e:
			print("Error Code 203 [OUT_EVENT_ERROR]: Error in Task Queue Controller out event PushObserver:", e)

class PushFailObserver():
	def next(self, value=None):
		controller_url = os.environ.get("API_SERVER_URL", "http://localhost:3032/fl_training_task_queue/run_cycle")
		try:
			print("Task Queue Controller raises push task fail")
			response = requests.post(controller_url, timeout=10)
			#===== need to report to AppPlat here =====#
			#
			#
			#
			#
			#=========================================#
		except Exception as e:
			print("Error Code 203 [OUT_EVENT_ERROR]: Error in Task Queue Controller out event PushFailObserver:", e)

class Observable():
	"""Observable implementation.
	"""

	def __init__(self):
		self.observers = []

	def next(self, value=None):
		"""Calls next function from every observer.
		"""
		for observer in self.observers:
			if observer is not None:
				if value is None:
					observer.next()
				else:
					observer.next(value)

	def subscribe(self, observer):
		"""Subscribe on specified observer.
		"""
		if observer is not None:
			self.observers.append(observer)
			return True
		return False

	def unsubscribe(self, observer):
		"""Unsubscribe from specified observer.
		"""
		if observer is None:
			return False
		if observer in self.observers:
			self.observers.remove(observer)
			return True
		return False
