"""Implementation for Observer and Observables used for out events.
Generated by itemis CREATE code generator.
"""
import subprocess
import logging
import os
import threading
import requests

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# class Observer():
# 	"""Observer implementation.
# 	"""

# 	def next(self, value=None):
# 		"""Abstract next method, which must be implemented."""
# 		raise NotImplementedError('user must define next() to use this base class')
	
class StartFlowerAppObserver():
	def next(self, value=None):
		api_server_url = os.environ.get("API_SERVER_URL", "http://localhost:9005")
		controller_url = f"{api_server_url}/fl_controller/start_flower_app"
		try:
			response = requests.post(controller_url, timeout=10)
			print("Flower Controller raises start flower app event")
		except Exception as e:
			print("Error Code 203 [OUT_EVENT_ERROR]: Error in Flower Controller out event StartFlowerAppObserver:", e)
	
class TerminateTrainingObserver():
	def next(self, value=None):
		api_server_url = os.environ.get("API_SERVER_URL", "http://localhost:9005")
		controller_url = f"{api_server_url}/fl_controller/terminate_training"
		try:
			response = requests.post(controller_url, timeout=10)
			print("Flower Controller raises terminate training event")
		except Exception as e:
			print("Error Code 203 [OUT_EVENT_ERROR]: Error in Flower Controller out event TerminateTrainingObserver:", e)
	
class CreateErrorLogObservableObserver():
	def next(self, value=None):
		api_server_url = os.environ.get("API_SERVER_URL", "http://localhost:9005")
		controller_url = f"{api_server_url}/fl_controller/create_error_log"
		try:
			response = requests.post(controller_url, timeout=10)
			print("Flower Controller raises create error log event")
		except Exception as e:
			print("Error Code 203 [OUT_EVENT_ERROR]: Error in Flower Controller out event CreateErrorLogObservableObserver:", e)
	
class TaskCompleteObserver():
	def next(self, value=None):
		api_server_url = os.environ.get("API_SERVER_URL", "http://localhost:9005")
		controller_url = f"{api_server_url}/fl_training_task_queue/complete"
		try:
			response = requests.post(controller_url, timeout=10)
			print("Flower Controller raises task complete event")
		except Exception as e:
			print("Error Code 203 [OUT_EVENT_ERROR]: Error in Flower Controller out event TaskCompleteObserver:", e)
	
class TaskErrorObserver():
	def next(self, value=None):
		api_server_url = os.environ.get("API_SERVER_URL", "http://localhost:9005")
		controller_url = f"{api_server_url}/fl_controller/send_error_log"
		controller_url2 = f"{api_server_url}/fl_training_task_queue/complete"
		try:
			response = requests.post(controller_url, timeout=10)
			response2 = requests.post(controller_url2, timeout=10)
			print("Flower Controller raises send error log event")
		except Exception as e:
			print("Error Code 203 [OUT_EVENT_ERROR]: Error in Flower Controller out event TaskErrorObserver:", e)


class Observable():
	"""Observable implementation.
	"""

	def __init__(self):
		self.observers = []

	def next(self, value=None):
		"""Calls next function from every observer.
		"""
		for observer in self.observers:
			if observer is not None:
				if value is None:
					observer.next()
				else:
					observer.next(value)

	def subscribe(self, observer):
		"""Subscribe on specified observer.
		"""
		if observer is not None:
			self.observers.append(observer)
			return True
		return False

	def unsubscribe(self, observer):
		"""Unsubscribe from specified observer.
		"""
		if observer is None:
			return False
		if observer in self.observers:
			self.observers.remove(observer)
			return True
		return False
